name: Check WordPress Version

# Should be cron
on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: getong/mariadb-action@v1.1

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v1
    ## @see https://github.com/gh640/github-actions-example-wordpress-plugin-update
    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        mv wp-cli.phar /usr/local/bin/wp

    - name: Install dependencies
      run: composer install

    - name: Check "Supported Up To" Value
      run: wp is-tested-up-to

    - name: Setup WP Tests
      if: ${{ failure() }}
      run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1

    - name: PHPUnit
      run: './vendor/bin/phpunit -c phpunit-integration.xml'
