name: Check WordPress Version

# Should be cron
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Not fail
        run: |
          exit 0
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [job1]
    if: always() && needs.job1.result == 'failure'
    steps:
      - name: Needs context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"

  check_version:
    runs-on: ubuntu-latest
    steps:
      ## Set up plugin
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3

      - name: Install Composer dependencies
        run: composer install

      ## Set up server
      - name: Start sever
        run: docker-compose up -d

      - name: Install WordPress
        run: docker-compose run wpcli wp core install --url=example.com --title=Example --admin_user=supervisor --admin_password=strongpassword --admin_email=info@example.com

      - name: Activate xCloner
        run: docker-compose run wpcli wp plugin activate xcloner

      ## Check if we're tested up to latest version of WordPress
      - name: Tested Up To Check
        run: docker-compose run wpcli wp is-tested-up-to

      ### If last step failed,
      - name: Update version
        if: ${{ failure() }}
        run: docker-compose run wpcli wp update-version
