name: Check WordPress Version

# Should be cron
on: [push]

env:
  WP_TESTS_DIR: /github/home/wp-tests/wordpress-tests-lib
  WP_CORE_DIR: /github/home/wp-tests/wordpress

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3

      ## Install
      - name: Install Composer dependencies
        run: composer install

      - name: Start docker-compose
        run: docker-compose up -d

      - name: Install WordPress
        run: docker-compose run wpcli wp core install --url=example.com --title=Example --admin_user=admin --admin_password=pass --admin_email=info@example.com

      - name: Activate xCloner
        run: docker-compose run wpcli wp plugin activate xcloner

      - name: Check version
        run: docker-compose run wpcli is-tested-up-to
